<!DOCTYPE HTML public "-w3c//dtd//xhtml 1.0 transitional//en" "http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Virtual Lab-Dayalbagh Educational Institute</title>
<link rel="shortcut icon" type="image/x-icon" href="images/icon.ico">
<link href="css/main.css" rel="stylesheet" type="text/css">
<link href="css/dropdown.css" media="all" rel="stylesheet" type="text/css" />
<link href="css/advanced.css" media="all" rel="stylesheet" type="text/css" />
<script language="javascript">
<!-- 
var isNS = (navigator.appName == "Netscape") ? 1 : 0;
  if(navigator.appName == "Netscape") document.captureEvents(Event.MOUSEDOWN||Event.MOUSEUP);
  function mischandler(){
   return false;
 }
  function mousehandler(e){
 	var myevent = (isNS) ? e : event;
 	var eventbutton = (isNS) ? myevent.which : myevent.button;
    if((eventbutton==2)||(eventbutton==3)) return false;
 }
 document.oncontextmenu = mischandler;
 document.onmousedown = mousehandler;
 document.onmouseup = mousehandler;
 
window.onload = init; 
function init() {
  disableDraggingFor(document.getElementById("draggingDisabled"));
} 
function disableDraggingFor(element) {
  // this works for FireFox and WebKit in future according to http://help.dottoro.com/lhqsqbtn.php
  element.draggable = false;
  // this works for older web layout engines
  element.onmousedown = function(event) {
                event.preventDefault();
                return false;
};
}
-->
</script>
</head>
<body id="draggingDisabled" bgcolor="#FFFFFF">
<div id="header_main"></div>
<div id="header">
<ul class="dropdown dropdown-horizontal">
<?php
ini_set("display_errors","Off");
	echo <<<EOQ
	<li><a href="home.php">Home</a></li>
	<li><a href="Stretchforming.php">Stretch Forming</a></li>
	<li class="dir"><a href="#">Simulations</a>
	<ul>
	<li><a href="StretchSimulation.php?Forming/Stretchforming/FormingStretch.mp4">STRETCH FORMING</a></li>
	<li><a href="StretchSimulation.php?Forming/Stretchforming/StretchGraph.mp4">STRETCH FORMING WITH GRAPH</a></li>
	<li><a href="StretchSimulation.php?Forming/Stretchforming/FormingStrain.mp4">STRETCH FORMING-2</a></li>
	<li><a href="StretchSimulation.php?Forming/Stretchforming/FormingGraph.mp4">STRETCH FORMING-2 WITH GRAPH</a></li>
	</ul>
	</li>
	<li><a href="MCQ_Stretchforming.php">Self Check Quiz</a></li>
EOQ;
?>
</ul></div>
<div><center>
<?php
	$value = $_SERVER['QUERY_STRING'];
	print <<<EOQ
	   <object id="player" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" name="player" width="1020" height="600"> 
		<param name="movie" value="player.swf"/> 
		<param name="allowfullscreen" value="true"/> 
		<param name="wmode" value="transparent"/>
		<param name="allowscriptaccess" value="always"/> 
		<param name="flashvars" value="file=$value&autostart=true&repeat=always&image=images/DEILOGO.jpg"/> 
		<embed 
			wmode="transparent"
			type="application/x-shockwave-flash"
			id="player2"
			name="player2"
			src="player.swf" 
			width="1020" 
			height="584"
			allowscriptaccess="always" 
			allowfullscreen="true"
			flashvars="file=$value&autostart=true&repeat=always&image=images/DEILOGO.jpg"/> 
	</object> 
EOQ;
if(stristr($value,FormingStretch))
{
?>
<table border="2" color="#ffffff" width="1020" style="background-color: white;">
<tr><td style="font-size: 1.2em; padding:5px; line-height:20px;">
Stretchforming process is a cold working bending process. In this video you can see a sheet is clamped with the help of bolts in clampers. The temperature of billet maintained to 20<sup>o</sup>C and material of the billet is carbon steel. Hydraulic press is used to deform the billet. The Lower die with hydraulic press compresses the billet 
with high force in upward direction and stretching take place in the sheet. Due to high deforming force and low temperature, material starts deforming plastically and at final step it has permanent elongation.On the Right side video you can see the system setup arrangement and the initial and final shape of the billet.
</td></tr></table>
<?php
}
else if(stristr($value,StretchGraph))
{
?>
<table border="2" color="#ffffff" width="1020" style="background-color: white;">
<tr><td style="font-size: 1.2em; padding:5px; line-height:20px;">
Stretch forming process is a cold working bending process. In this video you can see a sheet is clamped with the help of bolts in clampers. The temperature of billet maintained to 20<sup>o</sup>C and material of the billet is carbon steel. Hydraulic press is used to deform the billet. The Lower die with hydraulic press compresses the billet 
with high force in upward direction and stretching take place in the sheet. Equivalent strain in billet is shown over the left side of video. The graph between pilot height and forces generated by lower die are shownover right side of video. Due to high deforming force and low temperature, material starts deforming plastically and at final step it has permanent elongation.
</td></tr></table>
<?php
}
else if(stristr($value,FormingStrain))
{
?>
<table border="2" color="#ffffff" width="1020" style="background-color: white;">
<tr><td style="font-size: 1.2em; padding:5px; line-height:20px;">
In a given simulation of stretch forming, cold process is used. The seamless pipe is normally done in the single steps. Consider the various parameters of this simulation. The material of the billet is aluminium.The temperature of the billet is 20<sup>o</sup>C. 
In the simulation video the billet is divided into small finite element to have better analysis of the force. The hydraulic press is used for deformation. In the left hand side of the video we can see the processing of the stretch forming. 
In the right hand top side of the simulation video we can see the billet during the operation and final shape. In the right hand bottom side of the video one can depict the variation in the billet during the forming  operation.
</td></tr></table>
<?php
}
else if(stristr($value,FormingGraph))
{
?>
<table border="2" color="#ffffff" width="1020" style="background-color: white;">
<tr><td style="font-size: 1.2em; padding:5px; line-height:20px;">
In the left hand side of the video one can depict the variation of strain in the billet during the forming  operation. Initially the strain in the billet is zero while during the operation the strain rises due to deformation. It rises upto 0.16721. Greater strain indicates more deformation, more grain refinement and hence better mechanical properties. 
In the left hand side of the video one can depict the variation of strain with mesh  in the billet during the forming operation. In the right hand side of the video one can depict the variation of the temperature in the billet during the operation by the graph, the graph plot between the force and pilot height.
</td></tr></table>
<?php
}
?>
</center></div>
<div id="footer">
&copy; Metal Forming Virtual Simulation Lab - Dayalbagh Educational Institute (www.dei.ac.in)
</div>	
</body>
</html>